export const CONSTANTS = Object.freeze({
  PRODUCT_CONTROLLER_BASE_PATH: "/products",
  USER_CONTROLLER_BASE_PATH: "/users",
  WATCH_CONTROLLER_BASE_PATH: "/watching",
  MOCK_ALERT_PATH: "/mock-alert",
  PATH_WITH_ID: "/:id",
  NOT_FOUND_MESSAGE_BODY: "The requested resource was not found",
  DEFAULT_APP_NAME: "APP_NAME",
  DEFAULT_CONTEXT_PATH: "/",
  DEFAULT_NODE_ENV: "development",
  DEFAULT_SESSION: "SESSION",
  DEFAULT_LANGUAGES: ["en"],
  DEFAULT_LOG_LEVEL: "info",
  DEFAULT_PORT: 8001,
  DEFAULT_API_ENDPOINT: "http://localhost:8000",
  PAGE_NOT_FOUND: "page-not-found",
  PROBLEM_WITH_SERVICE: "problem-with-service",
  NO_ACCESS: "no-access",

});